
var game_file_list = [
    //以下为自动修改，请勿修改
    //----auto game_file_list start----
	"libs/modules/egret/egret.js",
	"libs/modules/egret/egret.native.js",
	"libs/modules/game/game.js",
	"libs/modules/res/res.js",
	"libs/modules/eui/eui.js",
	"libs/modules/tween/tween.js",
	"libs/modules/socket/socket.js",
	"other_libs/puremvc/puremvc.js",
	"other_libs/starlingSwf/starlingSwf.js",
	"bin-debug/base/BaseMediator.js",
	"bin-debug/module/dznn/view/GameBaseView.js",
	"bin-debug/module/srnn/untils/Srnn_sound_util.js",
	"bin-debug/net/BaseParse.js",
	"bin-debug/base/BaseLobbyMediator.js",
	"bin-debug/utils/AesClass/IVMode.js",
	"bin-debug/net/pro/DznnChipVo.js",
	"bin-debug/config/GameConfig.js",
	"bin-debug/config/GameInfoVO.js",
	"bin-debug/config/GameRoomVO.js",
	"bin-debug/config/MailVO.js",
	"bin-debug/config/PayCardVO.js",
	"bin-debug/config/RankVO.js",
	"bin-debug/Main.js",
	"bin-debug/module/alert/BusynessAlert.js",
	"bin-debug/module/alert/LoadingMask.js",
	"bin-debug/module/alert/TimingAlert.js",
	"bin-debug/module/AppFacade.js",
	"bin-debug/module/bbnn/BbnnMediator.js",
	"bin-debug/module/bbnn/view/BbnnView.js",
	"bin-debug/module/controller/ConfigDetect.js",
	"bin-debug/module/controller/ModelPrepCommand.js",
	"bin-debug/module/controller/StartupCommand.js",
	"bin-debug/module/controller/ViewPrepCommand.js",
	"bin-debug/module/dznn/DznnMediator.js",
	"bin-debug/module/dznn/GameAction.js",
	"bin-debug/module/dznn/GameStatus.js",
	"bin-debug/module/dznn/GameTime.js",
	"bin-debug/module/dznn/PokerAction.js",
	"bin-debug/module/dznn/view/DznnView.js",
	"bin-debug/AssetAdapter.js",
	"bin-debug/module/ftns/FtnsMediator.js",
	"bin-debug/module/ftns/untils/Ftns_sound_util.js",
	"bin-debug/module/ftns/view/FtnsBtn.js",
	"bin-debug/module/ftns/view/FtnsChip.js",
	"bin-debug/module/ftns/view/FtnsInfo.js",
	"bin-debug/module/ftns/view/FtnsPanel.js",
	"bin-debug/module/ftns/view/FtnsType.js",
	"bin-debug/module/ftns/view/FtnsView.js",
	"bin-debug/module/GameResourceManager.js",
	"bin-debug/module/GameSceneManager.js",
	"bin-debug/module/jqnn/JQNiuNiuMediator.js",
	"bin-debug/module/jqnn/untils/JQNiuNiuTimeNum.js",
	"bin-debug/module/jqnn/untils/Jqnn_sound_util.js",
	"bin-debug/module/jqnn/view/JQNiuNiuView.js",
	"bin-debug/module/lobby/interface/ILobbyScene.js",
	"bin-debug/module/lobby/LobbyMediator.js",
	"bin-debug/module/lobby/view/background/GameButtonRender.js",
	"bin-debug/module/lobby/view/background/HallButton.js",
	"bin-debug/module/lobby/view/background/LobbyHallBackground.js",
	"bin-debug/module/lobby/view/background/ScaleButton.js",
	"bin-debug/module/lobby/view/BankRecordListRender.js",
	"bin-debug/module/lobby/view/charge/ChargeContentRender.js",
	"bin-debug/module/lobby/view/charge/ChargeListItems.js",
	"bin-debug/module/lobby/view/GameGoldListRender.js",
	"bin-debug/module/lobby/view/GameRecordListRender.js",
	"bin-debug/module/lobby/view/GameRecordListRender2.js",
	"bin-debug/module/lobby/view/HeadListRender.js",
	"bin-debug/module/lobby/view/LobbyBankView.js",
	"bin-debug/module/lobby/view/LobbyChangeHeadView.js",
	"bin-debug/module/lobby/view/LobbyChargeView.js",
	"bin-debug/module/lobby/view/LobbyDuihuanListView.js",
	"bin-debug/module/lobby/view/LobbyExchangeListRender.js",
	"bin-debug/module/lobby/view/LobbyExChangeView.js",
	"bin-debug/module/lobby/view/LobbyMailView.js",
	"bin-debug/module/lobby/view/LobbyMainView.js",
	"bin-debug/module/lobby/view/LobbyPersonalView.js",
	"bin-debug/module/lobby/view/LobbyRankView.js",
	"bin-debug/module/lobby/view/LobbyRoomListView.js",
	"bin-debug/module/lobby/view/lobbySignWnd.js",
	"bin-debug/module/lobby/view/LobbySysCenterView.js",
	"bin-debug/module/lobby/view/LobbyView.js",
	"bin-debug/module/lobby/view/MailListRender.js",
	"bin-debug/module/lobby/view/RankListRender.js",
	"bin-debug/module/lobby/view/RoomlistRender.js",
	"bin-debug/module/login/LoginMediator.js",
	"bin-debug/module/login/model/vo/LoginVO.js",
	"bin-debug/module/login/view/LoginView.js",
	"bin-debug/module/niuniu/model/vo/ClientInfoVO.js",
	"bin-debug/module/niuniu/NiuNiuMediator.js",
	"bin-debug/module/niuniu/ui/HSliderGameSet.js",
	"bin-debug/module/niuniu/untils/GameWnd_util.js",
	"bin-debug/module/niuniu/untils/tbnn_numUIAssets.js",
	"bin-debug/module/niuniu/untils/tbnn_sound_util.js",
	"bin-debug/module/niuniu/untils/tbnn_Timers.js",
	"bin-debug/module/niuniu/view/GameHelp.js",
	"bin-debug/module/niuniu/view/GamePromptBox.js",
	"bin-debug/module/niuniu/view/GameSet.js",
	"bin-debug/module/niuniu/view/NiuButton.js",
	"bin-debug/module/niuniu/view/NiuImgJinbi.js",
	"bin-debug/module/niuniu/view/NiuNiuView.js",
	"bin-debug/module/niuniu/view/NiuType.js",
	"bin-debug/module/niuniu/view/TbNiuniuSeat.js",
	"bin-debug/module/niuniu/view/TopSet.js",
	"bin-debug/module/resload/loadingView.js",
	"bin-debug/module/resload/ResLoad.js",
	"bin-debug/module/srnn/SrnnMediator.js",
	"bin-debug/module/srnn/untils/Srnn_numUIAssets.js",
	"bin-debug/module/srnn/untils/Srnn_PokerAssets.js",
	"bin-debug/base/BaseProxy.js",
	"bin-debug/module/srnn/untils/Srnn_Timers.js",
	"bin-debug/module/srnn/view/SrnnButton.js",
	"bin-debug/module/srnn/view/SrnnChipsButtons.js",
	"bin-debug/module/srnn/view/SrnnView.js",
	"bin-debug/module/table/interface/ITable.js",
	"bin-debug/module/table/TableMediator.js",
	"bin-debug/module/table/view/Table2View.js",
	"bin-debug/module/table/view/Table4View.js",
	"bin-debug/module/table/view/Table6View.js",
	"bin-debug/module/table/view/TableView.js",
	"bin-debug/module/tbwz/TbwzMediator.js",
	"bin-debug/module/tbwz/view/DjsDraw.js",
	"bin-debug/module/tbwz/view/TbwzType.js",
	"bin-debug/module/tbwz/view/TbwzView.js",
	"bin-debug/base/PopUpManager.js",
	"bin-debug/net/GameSocket.js",
	"bin-debug/net/GameSocketConst.js",
	"bin-debug/net/LobbySocket.js",
	"bin-debug/net/pro/account_loginCS.js",
	"bin-debug/net/pro/account_loginSC.js",
	"bin-debug/net/pro/accountvo.js",
	"bin-debug/net/pro/AgrConditionVo.js",
	"bin-debug/net/pro/avatar_modifyCS.js",
	"bin-debug/net/pro/avatar_modifySC.js",
	"bin-debug/net/pro/AwardGoodsListVO.js",
	"bin-debug/net/pro/AwardGoodsRecordInfo.js",
	"bin-debug/net/pro/AwardGoodsRecordListVo.js",
	"bin-debug/net/pro/AwardGoodsVo.js",
	"bin-debug/net/pro/BankBindPhoneCS.js",
	"bin-debug/net/pro/BankerVo.js",
	"bin-debug/net/pro/BankLoginVo.js",
	"bin-debug/net/pro/BankRecordListVo.js",
	"bin-debug/net/pro/BankRecordVo.js",
	"bin-debug/net/pro/BbnnBankerVo.js",
	"bin-debug/net/pro/BbnnGameReEnterInfo.js",
	"bin-debug/net/pro/BbnnMoneyVo.js",
	"bin-debug/net/pro/BindEmailCodeVo.js",
	"bin-debug/net/pro/BindPhoneVo.js",
	"bin-debug/net/pro/ByteVo.js",
	"bin-debug/net/pro/change_agentCS.js",
	"bin-debug/net/pro/change_agentSC.js",
	"bin-debug/net/pro/ChangeAwardGoodsOrderVo.js",
	"bin-debug/net/pro/ChangeBankPasswordVo.js",
	"bin-debug/net/pro/ChangePasswordVo.js",
	"bin-debug/net/pro/ChangePwdPhoneEmailVo.js",
	"bin-debug/net/pro/ChipListVo.js",
	"bin-debug/net/pro/DeliverVo.js",
	"bin-debug/net/pro/DeskInfovo.js",
	"bin-debug/net/pro/DeskRankInfovo.js",
	"bin-debug/net/pro/display_mail_countSC.js",
	"bin-debug/net/pro/DznnBankerVo.js",
	"bin-debug/config/AccountData.js",
	"bin-debug/net/pro/DznnDealVo.js",
	"bin-debug/net/pro/DznnGameOverInfo.js",
	"bin-debug/net/pro/DznnGameReEnterInfo.js",
	"bin-debug/net/pro/DznnGameResultVo.js",
	"bin-debug/net/pro/DznnMoneyVo.js",
	"bin-debug/net/pro/DznnReEnterVo.js",
	"bin-debug/net/pro/DznnShowCardsVo.js",
	"bin-debug/net/pro/EmailCodeVo.js",
	"bin-debug/net/pro/FtnsAskBankerInfoVo.js",
	"bin-debug/net/pro/FtnsAskBankerSC.js",
	"bin-debug/net/pro/FtnsAskGetSC.js",
	"bin-debug/net/pro/FtnsAskShowSC.js",
	"bin-debug/net/pro/FtnsChipInCS.js",
	"bin-debug/net/pro/FtnsCommitSC.js",
	"bin-debug/net/pro/FtnsDealSC.js",
	"bin-debug/net/pro/FtnsGameOverInfoVo.js",
	"bin-debug/net/pro/FtnsGameOverSC.js",
	"bin-debug/net/pro/FtnsGetSC.js",
	"bin-debug/net/pro/FtnsReBankerCS.js",
	"bin-debug/net/pro/FtnsReEnter.js",
	"bin-debug/net/pro/FtnsReEnterInfoVo.js",
	"bin-debug/net/pro/FtnsShowCS.js",
	"bin-debug/net/pro/FtnsShowSC.js",
	"bin-debug/net/pro/FtnsStartChipSC.js",
	"bin-debug/net/pro/GameComeSC.js",
	"bin-debug/net/pro/GameEnterSC.js",
	"bin-debug/net/pro/GameLoginCS.js",
	"bin-debug/net/pro/GameMemberinfovo.js",
	"bin-debug/net/pro/gameMsgSC.js",
	"bin-debug/net/pro/GameRecordListVo.js",
	"bin-debug/net/pro/GameRecordVo.js",
	"bin-debug/net/pro/GameSitCS.js",
	"bin-debug/net/pro/GameUidSC.js",
	"bin-debug/net/pro/get_accountSC.js",
	"bin-debug/net/pro/get_userranksSC.js",
	"bin-debug/net/pro/GetAgrConditionVo.js",
	"bin-debug/net/pro/GetAwardGoodsRecordVo.js",
	"bin-debug/net/pro/GetAwardGoodsVo.js",
	"bin-debug/net/pro/GetGoldnnUinfoVo.js",
	"bin-debug/net/pro/GetShareAwardVo.js",
	"bin-debug/net/pro/GoldnnDaykListVo.js",
	"bin-debug/net/pro/GoldnnRankInfoVo.js",
	"bin-debug/net/pro/GoldnnUInfo.js",
	"bin-debug/net/pro/GoldnnUinfoListVo.js",
	"bin-debug/net/pro/GoldnnWeekListVo.js",
	"bin-debug/net/pro/guest_loginCS.js",
	"bin-debug/net/pro/guest_loginSC.js",
	"bin-debug/net/pro/JqnnDealVo.js",
	"bin-debug/net/pro/JqnnEndInfo.js",
	"bin-debug/net/pro/JqnnEndInfoListVo.js",
	"bin-debug/net/pro/JqnnLateInfo.js",
	"bin-debug/net/pro/JqnnLateInfoListVo.js",
	"bin-debug/net/pro/LoginFailedErrorSC.js",
	"bin-debug/net/pro/LoginSuccessSC.js",
	"bin-debug/net/pro/mail_deleteCS.js",
	"bin-debug/net/pro/mail_deleteSC.js",
	"bin-debug/net/pro/mail_listCS.js",
	"bin-debug/net/pro/mail_listSC.js",
	"bin-debug/net/pro/mail_readCS.js",
	"bin-debug/net/pro/mail_readSC.js",
	"bin-debug/net/pro/mail_writeCS.js",
	"bin-debug/net/pro/mail_writeSC.js",
	"bin-debug/net/pro/mailvo.js",
	"bin-debug/net/pro/MoneyListVo.js",
	"bin-debug/net/pro/MoneyVo.js",
	"bin-debug/net/pro/NickNameByUidCS.js",
	"bin-debug/net/pro/NumberVo.js",
	"bin-debug/net/pro/OnBeginSC.js",
	"bin-debug/net/pro/OnEndSC.js",
	"bin-debug/net/pro/OnSitdownSC.js",
	"bin-debug/net/pro/OnSitupSC.js",
	"bin-debug/net/pro/PageInfoVo.js",
	"bin-debug/net/pro/payrate_alipaySC.js",
	"bin-debug/net/pro/payrate_cardsuitSC.js",
	"bin-debug/net/pro/payrate_shengpaySC.js",
	"bin-debug/net/pro/PhoneVodeVo.js",
	"bin-debug/net/pro/PickShareAwardVo.js",
	"bin-debug/net/pro/QueryBankRecordVo.js",
	"bin-debug/net/pro/QueryGameRecordVo.js",
	"bin-debug/net/pro/QueryRoomVo.js",
	"bin-debug/net/pro/RankInfoVo.js",
	"bin-debug/net/pro/rankvo.js",
	"bin-debug/net/pro/ResultVo.js",
	"bin-debug/net/pro/RoomInfoListVo.js",
	"bin-debug/net/pro/RoomInfoVo.js",
	"bin-debug/net/pro/SafeAccountInfoVo.js",
	"bin-debug/net/pro/seatInfovo.js",
	"bin-debug/net/pro/SeatlistSC.js",
	"bin-debug/net/pro/SendBankBindCodeCS.js",
	"bin-debug/net/pro/SendPhoneCharcodeVo.js",
	"bin-debug/net/pro/SetAwardGoodsOrderVo.js",
	"bin-debug/net/pro/ShareAwardVo.js",
	"bin-debug/net/pro/SignAwardInfoVo.js",
	"bin-debug/net/pro/SrnnDealVo.js",
	"bin-debug/net/pro/SrnnEndInfo.js",
	"bin-debug/net/pro/SrnnEndInfoListVo.js",
	"bin-debug/net/pro/SrnnLateInfo.js",
	"bin-debug/net/pro/SrnnLaterVo.js",
	"bin-debug/net/pro/SrnnOkVo.js",
	"bin-debug/net/pro/StartChipVo.js",
	"bin-debug/net/pro/StatusVo.js",
	"bin-debug/net/pro/StringVo.js",
	"bin-debug/net/pro/SuitVo.js",
	"bin-debug/net/pro/SuitVoArr.js",
	"bin-debug/net/pro/TbnnDealSC.js",
	"bin-debug/net/pro/TbnnEndInfovo.js",
	"bin-debug/net/pro/TbnnEndSC.js",
	"bin-debug/net/pro/TbnnLateInfosvo.js",
	"bin-debug/net/pro/TbnnLateSC.js",
	"bin-debug/net/pro/TbwzDealVo.js",
	"bin-debug/net/pro/TbwzLateInfo.js",
	"bin-debug/net/pro/TbwzLateInfoListVo.js",
	"bin-debug/net/pro/TreasureToMobileFareVo.js",
	"bin-debug/net/pro/UpdateIntomoneySC.js",
	"bin-debug/net/ProtobufferConst.js",
	"bin-debug/net/ProtocolStatus.js",
	"bin-debug/net/SockeUtils.js",
	"bin-debug/notify/LobbyNotify.js",
	"bin-debug/notify/SysNotify.js",
	"bin-debug/sound/GameSound.js",
	"bin-debug/sound/SoundManager.js",
	"bin-debug/ThemeAdapter.js",
	"bin-debug/utils/AesClass/AESKey.js",
	"bin-debug/utils/AesClass/Base64.js",
	"bin-debug/utils/AesClass/CBCMode.js",
	"bin-debug/utils/AesClass/IPRNG.js",
	"bin-debug/config/AccountVO.js",
	"bin-debug/utils/AesClass/NullPad.js",
	"bin-debug/utils/AesClass/PKCS5.js",
	"bin-debug/utils/AesClass/Random.js",
	"bin-debug/utils/Animation.js",
	"bin-debug/utils/Constants.js",
	"bin-debug/utils/GameUtils.js",
	"bin-debug/utils/LabelTool.js",
	"bin-debug/utils/MoneyUtils.js",
	"bin-debug/utils/NativeApi.js",
	"bin-debug/utils/NumUI.js",
	"bin-debug/utils/PaiTurn.js",
	"bin-debug/utils/PanelEffUntils.js",
	"bin-debug/utils/Poker2Assets.js",
	"bin-debug/utils/PokerAnimation.js",
	"bin-debug/utils/PokerAssets.js",
	"bin-debug/utils/Queue.js",
	"bin-debug/utils/RegUtils.js",
	"bin-debug/utils/ServerConstants.js",
	"bin-debug/utils/SoundControl.js",
	"bin-debug/utils/StringUtil.js",
	"bin-debug/utils/SwfManager.js",
	"bin-debug/utils/Timers.js",
	"bin-debug/utils/TimersCircle.js",
	"bin-debug/utils/VersionControl.js",
	//----auto game_file_list end----
];

var window = this;

egret_native.setSearchPaths([""]);

egret_native.requireFiles = function () {
    for (var key in game_file_list) {
        var src = game_file_list[key];
        require(src);
    }
};

egret_native.egretInit = function () {
    egret_native.requireFiles();
    egret.TextField.default_fontFamily = "/system/fonts/DroidSansFallback.ttf";
    //egret.dom为空实现
    egret.dom = {};
    egret.dom.drawAsCanvas = function () {
    };
};

egret_native.egretStart = function () {
    var option = {
        //以下为自动修改，请勿修改
        //----auto option start----
		entryClassName: "Main",
		frameRate: 30,
		scaleMode: "showAll",
		contentWidth: 1080,
		contentHeight: 1920,
		showPaintRect: false,
		showFPS: false,
		fpsStyles: "x:0,y:0,size:40,textColor:0xffffff,bgAlpha:0.7",
		showLog: false,
		logFilter: "",
		maxTouches: 2,
		textureScaleFactor: 1
		//----auto option end----
    };

    egret.native.NativePlayer.option = option;
    egret.runEgret();
    egret_native.Label.createLabel(egret.TextField.default_fontFamily, 20, "", 0);
    egret_native.EGTView.preSetOffScreenBufferEnable(true);
};